project:
  type: book
  output-dir: output/

book:
  title: metaSurvey
  subtitle: Paquete de R para el procesamiento de encuestas por muestreo con generación de recetas mediante metaprogramación y estimación de varianzas.
  author:
    name: Mauro Loprete
    url: http://www.janedoe.com
  cover-image: images/logo.png
  downloads: [pdf]
  abstract: "El trabajo presenta metaSurvey, un paquete de R diseñado para mejorar el procesamiento de encuestas por muestreo y la estimación de parámetros poblacionales. Utiliza metaprogramación y técnicas de remuestreo para ofrecer resultados precisos, evaluar la incertidumbre y fomentar la reproducibilidad. A diferencia de otras bibliotecas, metaSurvey combina flexibilidad mediante metaprogramación con las capacidades de procesamiento de encuestas del paquete survey. Los objetivos incluyen proporcionar una herramienta útil, incorporar técnicas de remuestreo para usuarios no expertos, permitir la generación de 'recetas' personalizadas, y fomentar la contribución de la comunidad. Se destaca como alternativa a paquetes propietarios, enfocándose en la transparencia y reproducibilidad para mejorar la confiabilidad de las estimaciones poblacionales."
  chapters:
    - index.qmd
  appendices:
    - Appendices/AppendixA.qmd

  site-url: https://github.com/metaSurveyR/metaSurvey
  repo-url: https://https://github.com/metaSurveyR
  repo-actions: [edit, source, issue]
  search: true


thesis:
  supervisor: 
    name: Dra. Natalia da Silva
  degree-name: Licenciado en Estadística
  university: Universidad de la República
  department: Instituto de Estadística
  date: Marzo de 2024
  group: I
  faculty: Facultad de Ciencias Económicas y de Administración
  #quotation:
  #  text: "Thanks to my solid academic training, today I can write hundreds of words on virtually any topic without possessing a shred of information, which is how I got a good job in journalism."
  #  attribution: Dave Barry
  acknowledgements: "Frontmatter/acknowledgements.tex"
  #abbreviations: "Frontmatter/abbreviations.tex"
  #symbols: "Frontmatter/symbols.tex"
  dedication: "Frontmatter/dedication.tex"

bibliography: [example.bib]

execute:
  echo: false
  code-overflow: wrap

# urlcolor changes the url color in the body of the PDF
# linkcolor changes color of internal links (like to figures)
# toclinkcolor changes color of toc, lof and lot links
format:
  quarto-thesis-pdf: 
    urlcolor: red
    toclinkcolor: black
    toc-depth: 2
  html:
    theme: cosmo
